# Generated by Django 4.2.3 on 2023-08-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
        migrations.AddField(
            model_name='movie',
            name='duration2',
            field=models.IntegerField(default=0, verbose_name='duration'),
        ),
    ]
