# Generated by Django 4.2.3 on 2023-08-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0002_remove_movie_duration_movie_duration2'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='file',
            field=models.FileField(default='', upload_to='movies/videos/'),
            preserve_default=False,
        ),
    ]
