# Generated by Django 4.2.3 on 2023-08-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0005_alter_movie_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
